Feature is export image
ibm-vpc/terraform-provider-ibm pull request #124
Opened 2022-04-26 12:07 UTC by deepaksibm

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2023-02-09 03:09 UTC, deepaksibm commented
```

$ tfpt TestAccIBMIsImageExportsDataSourceAllArgs
=== RUN   TestAccIBMIsImageExportsDataSourceAllArgs
--- PASS: TestAccIBMIsImageExportsDataSourceAllArgs (35.08s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc	36.621s
$ tfpt TestAccIBMIsImageExportDataSourceAllArgs
=== RUN   TestAccIBMIsImageExportDataSourceAllArgs
--- PASS: TestAccIBMIsImageExportDataSourceAllArgs (31.44s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc	33.033s

$ tfpt TestAccIBMIsImageExportBasic
=== RUN   TestAccIBMIsImageExportBasic
--- PASS: TestAccIBMIsImageExportBasic (27.42s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc	28.688s

$ tfpt TestAccIBMIsImageExportAllArgs
=== RUN   TestAccIBMIsImageExportAllArgs
--- PASS: TestAccIBMIsImageExportAllArgs (47.76s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc	49.006s
```

2023-02-10 14:20 UTC, deepaksibm commented
Terraform out put from prod us-south
```


# data.ibm_is_image_export_job.example:
data "ibm_is_image_export_job" "example" {
    created_at       = "2023-02-10T14:18:16.000Z"
    format           = "qcow2"
    href             = "https://us-south.iaas.cloud.ibm.com/v1/images/r006-ab0d67c1-092d-4ec8-9828-b7a2a6a78097/export_jobs/r006-10ed893b-d1fc-4047-951a-f757c8307fab"
    id               = "r006-ab0d67c1-092d-4ec8-9828-b7a2a6a78097/r006-10ed893b-d1fc-4047-951a-f757c8307fab"
    image            = "r006-ab0d67c1-092d-4ec8-9828-b7a2a6a78097"
    image_export_job = "r006-10ed893b-d1fc-4047-951a-f757c8307fab"
    name             = "tfp-test-image-export-updated"
    resource_type    = "image_export_job"
    status           = "queued"
    status_reasons   = []
    storage_bucket   = [
        {
            crn  = "crn:v1:bluemix:public:cloud-object-storage:global:a/7f75c7b025e54bc5635f754b2f888665:087107de-d3c9-42a5-b00f-0480818017a1:bucket:customimage0731"
            name = "customimage0731"
        },
    ]
    storage_href     = "cos://us-south/customimage0731/test-bhavesh-img-tfp-test-image-export-updated.qcow2"
    storage_object   = [
        {
            name = "test-bhavesh-img-tfp-test-image-export-updated.qcow2"
        },
    ]
}

# data.ibm_is_image_export_jobs.example:
data "ibm_is_image_export_jobs" "example" {
    export_jobs = [
        {
            completed_at       = ""
            created_at         = "2023-02-10T14:18:16.000Z"
            encrypted_data_key = ""
            format             = "qcow2"
            href               = "https://us-south.iaas.cloud.ibm.com/v1/images/r006-ab0d67c1-092d-4ec8-9828-b7a2a6a78097/export_jobs/r006-10ed893b-d1fc-4047-951a-f757c8307fab"
            image_export_job   = "r006-10ed893b-d1fc-4047-951a-f757c8307fab"
            name               = "tfp-test-image-export-updated"
            resource_type      = "image_export_job"
            started_at         = ""
            status             = "queued"
            status_reasons     = []
            storage_bucket     = [
                {
                    crn  = "crn:v1:bluemix:public:cloud-object-storage:global:a/7f75c7b025e54bc5635f754b2f888665:087107de-d3c9-42a5-b00f-0480818017a1:bucket:customimage0731"
                    name = "customimage0731"
                },
            ]
            storage_href       = "cos://us-south/customimage0731/test-bhavesh-img-tfp-test-image-export-updated.qcow2"
            storage_object     = [
                {
                    name = "test-bhavesh-img-tfp-test-image-export-updated.qcow2"
                },
            ]
        },
        {
            completed_at       = "2023-02-10T05:53:18.000Z"
            created_at         = "2023-02-10T05:52:45.000Z"
            encrypted_data_key = ""
            format             = "qcow2"
            href               = "https://us-south.iaas.cloud.ibm.com/v1/images/r006-ab0d67c1-092d-4ec8-9828-b7a2a6a78097/export_jobs/r006-5d87fd6a-d676-47c0-bedb-91636c7dec03"
            image_export_job   = "r006-5d87fd6a-d676-47c0-bedb-91636c7dec03"
            name               = "test-bhavesh-img-frozen-legislate-tree-architect-charger"
            resource_type      = "image_export_job"
            started_at         = "2023-02-10T05:52:51.000Z"
            status             = "succeeded"
            status_reasons     = []
            storage_bucket     = [
                {
                    crn  = "crn:v1:bluemix:public:cloud-object-storage:global:a/7f75c7b025e54bc5635f754b2f888665:087107de-d3c9-42a5-b00f-0480818017a1:bucket:customimage0731"
                    name = "customimage0731"
                },
            ]
            storage_href       = "cos://us-south/customimage0731/test-bhavesh-img-test-bhavesh-img-frozen-legislate-tree-architect-charger.qcow2"
            storage_object     = [
                {
                    name = "test-bhavesh-img-test-bhavesh-img-frozen-legislate-tree-architect-charger.qcow2"
                },
            ]
        },
    ]
    id          = "2023-02-10 14:18:20.21483 +0000 UTC"
    image       = "r006-ab0d67c1-092d-4ec8-9828-b7a2a6a78097"
}

# ibm_is_image_export_job.example:
resource "ibm_is_image_export_job" "example" {
    created_at       = "2023-02-10T14:18:16.000Z"
    format           = "qcow2"
    href             = "https://us-south.iaas.cloud.ibm.com/v1/images/r006-ab0d67c1-092d-4ec8-9828-b7a2a6a78097/export_jobs/r006-10ed893b-d1fc-4047-951a-f757c8307fab"
    id               = "r006-ab0d67c1-092d-4ec8-9828-b7a2a6a78097/r006-10ed893b-d1fc-4047-951a-f757c8307fab"
    image            = "r006-ab0d67c1-092d-4ec8-9828-b7a2a6a78097"
    image_export_job = "r006-10ed893b-d1fc-4047-951a-f757c8307fab"
    name             = "tfp-test-image-export-updated"
    resource_type    = "image_export_job"
    status           = "queued"
    status_reasons   = []
    storage_href     = "cos://us-south/customimage0731/test-bhavesh-img-tfp-test-image-export-updated.qcow2"
    storage_object   = [
        {
            name = "test-bhavesh-img-tfp-test-image-export-updated.qcow2"
        },
    ]

    storage_bucket {
        crn  = "crn:v1:bluemix:public:cloud-object-storage:global:a/7f75c7b025e54bc5635f754b2f888665:087107de-d3c9-42a5-b00f-0480818017a1:bucket:customimage0731"
        name = "customimage0731"
    }
}
```

2023-02-10 14:51 UTC, deepaksibm commented
Acceptance test results on prod us-south

```

$ tfpt TestAccIBMIsImageExportBasic
--- PASS: TestAccIBMIsImageExportBasic (33.21s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     34.448s

$tfpt TestAccIBMIsImageExportAllArgs
=== RUN   TestAccIBMIsImageExportAllArgs
--- PASS: TestAccIBMIsImageExportAllArgs (47.71s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     48.972s

$ tfpt TestAccIBMIsImageExportDataSourceAllArgs
=== RUN   TestAccIBMIsImageExportDataSourceAllArgs
--- PASS: TestAccIBMIsImageExportDataSourceAllArgs (66.70s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     67.659s

$ tfpt TestAccIBMIsImageExportsDataSourceAllArgs
=== RUN   TestAccIBMIsImageExportsDataSourceAllArgs
--- PASS: TestAccIBMIsImageExportsDataSourceAllArgs (35.09s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     36.054s
```

2023-02-17 04:38 UTC, SunithaGudisagarIBM requested changes
Hi Deepak, 

Please find my review comments here.
After incorporation this PR is ready to go to upstream.

Thank you
Sunitha

2023-02-17 04:38 UTC, SunithaGudisagarIBM commented on website/docs/r/is_image_export_job.html.markdown
> +Provides a resource for ImageExportJob. This allows ImageExportJob to be created, updated and deleted.
Please add the link to documentation here

2023-02-17 04:38 UTC, SunithaGudisagarIBM commented on website/docs/d/is_image_export.html.markdown
> +Provides a read-only data source for ImageExportJob. You can then reference the fields of the data source in other resources within the same configuration using interpolation syntax.
Please add the link to documentation here

2023-02-17 04:38 UTC, SunithaGudisagarIBM commented on website/docs/d/is_image_exports.html.markdown
> +Provides a read-only data source for ImageExportJobUnpaginatedCollection. You can then reference the fields of the data source in other resources within the same configuration using interpolation syn
Please add the link to documentation here

2023-02-17 04:38 UTC, SunithaGudisagarIBM commented on website/docs/d/is_image_export.html.markdown
> +  name = "my-image-export"
example

2023-02-17 04:38 UTC, SunithaGudisagarIBM commented on website/docs/d/is_image_exports.html.markdown
> +  name = "my-image-export"
example

2023-02-17 04:38 UTC, SunithaGudisagarIBM commented on website/docs/d/is_image_exports.html.markdown
> +	image = ibm_is_image_export_job.example.id
execute terraform fmt on examples

2023-02-17 04:38 UTC, SunithaGudisagarIBM commented on website/docs/r/is_image_export_job.html.markdown
> +  name = "my-image-export"
example

2023-02-17 04:38 UTC, SunithaGudisagarIBM commented on ibm/acctest/acctest.go
> -		IsImage = "r006-13938c0a-89e4-4370-b59b-55cd1402562d" // for next gen infrastructure
please remove this when you are taking this PR to upstream

2023-04-11 11:12 UTC, SunithaGudisagarIBM1 commented on ibm/service/vpc/resource_ibm_is_image_export_job.go
> +	torageBucket := &vpcv1.CloudObjectStorageBucketIdentity{}
storage*

2023-06-09 14:32 UTC, closed without merging