metadata post ga changes in instance
ibm-vpc/terraform-provider-ibm pull request #153
Opened 2022-07-06 11:45 UTC by deepaksibm

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2022-07-26 18:49 UTC, astha-jain commented on website/docs/r/is_instance.html.markdown
> +- `metadata_service` - (Optional, String) The metadata service configuration.
(Optional, String) - not a string

2023-01-29 20:25 UTC, deepaksibm commented
In prod  -  vpcdemo
```

$ tfpt TestAccIBMISInstance_metadata_service
=== RUN   TestAccIBMISInstance_metadata_service
no message sent


no message sent
--- PASS: TestAccIBMISInstance_metadata_service (364.52s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     366.077s
```

2023-01-31 13:40 UTC, SunithaGudisagarIBM reviewed
Please find my comment Deepak

Thank you
Sunitha

2023-01-31 13:40 UTC, SunithaGudisagarIBM commented on ibm/service/vpc/resource_ibm_is_instance_template.go
> -				Type:        schema.TypeBool,
Can we add acceptance test for instance template also?

2023-02-01 10:07 UTC, SunithaGudisagarIBM commented
Please do make fmt and push the code
<img width="664" alt="Screenshot 2023-02-01 at 3 37 03 PM" src="https://user-images.githubusercontent.com/78336632/216013195-c1332e47-7e20-4592-82c7-9afee033890d.png">

2023-02-01 12:25 UTC, SunithaGudisagarIBM commented on ibm/acctest/acctest.go
> +		IsImage = "r134-5800d6ef-ad8b-464e-b242-e69e43b93aea" // for next gen infrastructure
Revert changes once testing is done

2023-02-01 12:28 UTC, SunithaGudisagarIBM commented
```
resource "ibm_is_instance" "testacc_instance" {
  name    = "sunitha-image"
  image   = "r006-b4d8d8d4-7768-4a1b-9434-9483ca821a0d"
  profile = "cx2-2x4"
  primary_network_interface {
    subnet = "0717-cd4f74f1-bfae-423a-886b-9163256ec4a9"
  }
  vpc  = "r006-0d37163a-701d-4ad6-9ece-a3e34cf28935"
  zone = "us-south-1"
  keys = ["r006-d3f8e88f-1adb-4c4b-973c-47dc68097343"]
  network_interfaces {
    subnet = "0717-cd4f74f1-bfae-423a-886b-9163256ec4a9"
    name   = "eth1"
  }
  metadata_service {
    response_hop_limit = 2
  }
}
```

<img width="1061" alt="Screenshot 2023-02-01 at 5 58 10 PM" src="https://user-images.githubusercontent.com/78336632/216042467-40a02a1b-fb9c-44bf-8496-e4c71a5686ae.png">
<img width="593" alt="Screenshot 2023-02-01 at 5 58 24 PM" src="https://user-images.githubusercontent.com/78336632/216042519-aa1cede3-ac0c-4117-a76c-c23290745fcc.png">

2023-02-01 12:42 UTC, SunithaGudisagarIBM commented
```
resource "ibm_is_instance_template" "instancetemplate1" {
  name    = "sunitha-instance-temp"
  image   = "r006-b4d8d8d4-7768-4a1b-9434-9483ca821a0d"
  profile = "cx2-2x4"

  primary_network_interface {
    subnet = "0717-cd4f74f1-bfae-423a-886b-9163256ec4a9"
  }

  vpc  = "r006-0d37163a-701d-4ad6-9ece-a3e34cf28935"
  zone = "us-south-1"
  keys = ["r006-d3f8e88f-1adb-4c4b-973c-47dc68097343"]
}
```

2023-02-01 12:47 UTC, SunithaGudisagarIBM requested changes
Please my comments

Thanks and Regards
Sunitha

2023-02-01 12:47 UTC, SunithaGudisagarIBM commented on ibm/service/vpc/data_source_ibm_is_instance_template.go
> +			isInstanceMetadataService: {
Please add the schema for metadata service here

2023-02-01 12:47 UTC, SunithaGudisagarIBM commented on ibm/service/vpc/data_source_ibm_is_instance_templates.go
> +
Please add the schema for metadata service here

2023-02-01 12:47 UTC, SunithaGudisagarIBM commented on ibm/service/vpc/data_source_ibm_is_instance_templates.go
> +
Templates is not returning anything please check

 data.ibm_is_instance_templates.instance_templates_data:
data "ibm_is_instance_templates" "instance_templates_data" {
    id = "2023-02-01 12:43:06.68559 +0000 UTC"
}

2023-02-01 12:54 UTC, SunithaGudisagarIBM requested changes

2023-02-01 12:54 UTC, SunithaGudisagarIBM commented on ibm/service/vpc/data_source_ibm_is_instance_templates.go
> +
There are multiple places you need to add the logic, ex : line number 770, Please check in all the data sources,
As of now the values are not getting populated in any of the data sources

				if instance.MetadataService != nil {
					d.Set(isInstanceTemplateMetadataServiceEnabled, instance.MetadataService.Enabled)
				}

2023-02-01 12:54 UTC, SunithaGudisagarIBM commented on ibm/service/vpc/data_source_ibm_is_instance.go
> +			isInstanceMetadataService: {
As of now the values are not getting populated in any of the data sources, Please review the changes again

2023-02-01 12:54 UTC, SunithaGudisagarIBM commented on ibm/service/vpc/data_source_ibm_is_instances.go
> +							Type:        schema.TypeList,
As of now the values are not getting populated in any of the data sources, Please review the changes again

2023-02-03 13:55 UTC, deepaksibm commented
```
$ tfpt TestAccIBMISInstanceTemplate_metadata_service
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./ibm/service/vpc -v -run=TestAccIBMISInstanceTemplate_metadata_service -timeout 700m
=== RUN   TestAccIBMISInstanceTemplate_metadata_service
--- PASS: TestAccIBMISInstanceTemplate_metadata_service (825.51s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     827.074s
```

2023-02-03 14:03 UTC, deepaksibm commented
address all the comments

2023-02-06 10:17 UTC, SunithaGudisagarIBM commented
After Review 
```
resource "ibm_is_instance" "testacc_instance" {
  name    = "sunitha-image"
  image   = "r006-b4d8d8d4-7768-4a1b-9434-9483ca821a0d"
  profile = "cx2-2x4"
  primary_network_interface {
    subnet = "0717-cd4f74f1-bfae-423a-886b-9163256ec4a9"
  }
  vpc  = "r006-0d37163a-701d-4ad6-9ece-a3e34cf28935"
  zone = "us-south-1"
  keys = ["r006-720a844d-4083-4353-a4d5-fe055737deef"]
  network_interfaces {
    subnet = "0717-cd4f74f1-bfae-423a-886b-9163256ec4a9"
    name   = "eth1"
  }
}
data "ibm_is_instances" "ds_instances" {
}

data "ibm_is_instance" "ds_instance" {
  name = "sunitha-image"
}
```
Resource -
<img width="685" alt="Screenshot 2023-02-06 at 3 46 20 PM" src="https://user-images.githubusercontent.com/78336632/216945725-cb0710f1-fa85-4b8f-a602-5d89e91b8f42.png">

Datasource -
<img width="663" alt="Screenshot 2023-02-06 at 3 46 53 PM" src="https://user-images.githubusercontent.com/78336632/216945843-1b38477a-cbd7-4d4e-ba47-0dc085e9c2b8.png">
<img width="803" alt="Screenshot 2023-02-06 at 3 47 26 PM" src="https://user-images.githubusercontent.com/78336632/216945964-2d6365cc-7c31-4169-8af1-02ddab587994.png">

2023-02-06 10:21 UTC, SunithaGudisagarIBM commented
Template test after code review changes :

```
resource "ibm_is_instance_template" "instancetemplate1" {
  name    = "sunitha-instance-temp"
  image   = "r006-b4d8d8d4-7768-4a1b-9434-9483ca821a0d"
  profile = "cx2-2x4"

  primary_network_interface {
    subnet = "0717-cd4f74f1-bfae-423a-886b-9163256ec4a9"
  }

  vpc  = "r006-0d37163a-701d-4ad6-9ece-a3e34cf28935"
  zone = "us-south-1"
  keys = ["r006-720a844d-4083-4353-a4d5-fe055737deef"]
  metadata_service {
    enabled            = true
    protocol           = "http"
    response_hop_limit = 2
  }
}

data "ibm_is_instance_template" "instance_template_data" {
  name = "sunitha-instance-temp"
}

data "ibm_is_instance_templates" "instance_templates_data" {
}
```

resource output:
<img width="604" alt="Screenshot 2023-02-06 at 3 49 44 PM" src="https://user-images.githubusercontent.com/78336632/216946458-48bc9145-6ec8-4c7b-8f48-9862d92f6aec.png">

datasource output:
<img width="769" alt="Screenshot 2023-02-06 at 3 50 56 PM" src="https://user-images.githubusercontent.com/78336632/216946706-22b99a95-b313-4613-96dc-62b7682584cf.png">

<img width="609" alt="Screenshot 2023-02-06 at 3 51 11 PM" src="https://user-images.githubusercontent.com/78336632/216946762-944091f3-5b15-4afc-b717-46755497d6a8.png">

2023-02-06 10:22 UTC, SunithaGudisagarIBM approved these changes
Hi Deepak, 

Code changes seems to be fine for me.

Thank you
Sunitha

2023-02-17 04:35 UTC, deepaksibm commented
going upstream

2023-02-17 04:35 UTC, closed without merging