Doc corrections for resource group to intimate id and subnet floating ip changes
ibm-vpc/terraform-provider-ibm pull request #173
Opened 2022-09-05 05:53 UTC by BShrivastav

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000
https://jiracloud.swg.usma.ibm.com:8443/browse/UI-25139
https://jiracloud.swg.usma.ibm.com:8443/browse/UI-25108

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2022-09-09 11:38 UTC, ujjwal-ibm requested changes

2022-09-09 11:38 UTC, ujjwal-ibm commented on website/docs/d/is_backup_policies.html.markdown
> +    - `resource_group` - (List) The Resource group, for this backup policy.
*resource group object

2022-09-09 11:38 UTC, ujjwal-ibm commented on website/docs/d/is_ipsec_policies.html.markdown
> +	- `resource_group` - (Required, List) The resource group id, for this IPsec policy.
object

2022-09-09 11:38 UTC, ujjwal-ibm commented on website/docs/d/is_ipsec_policy.html.markdown
> +- `resource_group` - (List) The resource group id, for this IPsec policy.
object

2022-09-12 06:11 UTC, ujjwal-ibm commented on website/docs/d/is_ipsec_policies.html.markdown
> +	- `resource_group` - (Required, List) The resource group id, for this IPsec policy.
remove required from all attributes

2022-09-12 06:22 UTC, BShrivastav commented on website/docs/d/is_backup_policies.html.markdown
> +    - `resource_group` - (List) The Resource group, for this backup policy.
done.

2022-09-14 05:45 UTC, BShrivastav commented
Raised Upstream - https://github.com/IBM-Cloud/terraform-provider-ibm/pull/4025

2022-09-14 05:45 UTC, closed without merging