Security Group Rule ICMP Type, Code -> Any
ibm-vpc/terraform-provider-ibm pull request #203
Opened 2022-11-22 08:37 UTC by SunithaGudisagarIBM

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISSecurityGroupRule_basic'

```
<img width="710" alt="Screenshot 2022-11-22 at 12 33 16 PM" src="https://user-images.githubusercontent.com/78336632/203265639-a37a8260-2b80-4854-baeb-2c8c6ffc0504.png">

```
resource "ibm_is_vpc" "testacc_vpc" {
  name = "sunitha"
}

resource "ibm_is_security_group" "testacc_security_group" {
  name = "sunitha-sg"
  vpc  = ibm_is_vpc.testacc_vpc.id
}

resource "ibm_is_security_group_rule" "testacc_security_group_rule_all" {
  group     = ibm_is_security_group.testacc_security_group.id
  direction = "inbound"
  remote    = "127.0.0.1"
}

resource "ibm_is_security_group_rule" "testacc_security_group_rule_icmp" {
  group     = ibm_is_security_group.testacc_security_group.id
  direction = "inbound"
  remote    = "127.0.0.1"
  icmp {
    code = 256
    type = 30
  }
}
resource "ibm_is_security_group_rule" "testacc_security_group_rule_icmp_any" {
  group     = ibm_is_security_group.testacc_security_group.id
  direction = "inbound"
  remote    = "127.0.0.1"
  icmp {
    # code = 256
    # type = 30
  }
}

resource "ibm_is_security_group_rule" "testacc_security_group_rule_tcp" {
  group     = ibm_is_security_group.testacc_security_group.id
  direction = "inbound"
  remote    = "127.0.0.1"
  tcp {
    # code = 256
    # type = 30
  }
}

data "ibm_is_security_group_rules" "example" {
  security_group = ibm_is_security_group.testacc_security_group.id
}

data "ibm_is_security_group_rule" "example" {
  security_group_rule = ibm_is_security_group_rule.testacc_security_group_rule_icmp.rule_id
  security_group      = ibm_is_security_group.testacc_security_group.id
}
```

2022-11-22 08:41 UTC, SunithaGudisagarIBM commented
```
sunitha@Sunithas-MacBook-Pro vpc-ibm-lb-config % terraform show
# data.ibm_is_security_group_rule.example:
data "ibm_is_security_group_rule" "example" {
    code                = 256
    direction           = "inbound"
    href                = "https://us-south.iaas.cloud.ibm.com/v1/security_groups/r006-1f31afb0-416e-4ddc-9a04-1f87343aa8fd/rules/r006-0e257e96-ac9e-4861-921d-0823501cf025"
    id                  = "r006-0e257e96-ac9e-4861-921d-0823501cf025"
    ip_version          = "ipv4"
    protocol            = "icmp"
    remote              = [
        {
            address    = "127.0.0.1"
            cidr_block = ""
            crn        = ""
            deleted    = []
            href       = ""
            id         = ""
            name       = ""
        },
    ]
    security_group      = "r006-1f31afb0-416e-4ddc-9a04-1f87343aa8fd"
    security_group_rule = "r006-0e257e96-ac9e-4861-921d-0823501cf025"
    type                = 30
}
```

2022-11-22 09:26 UTC, SunithaGudisagarIBM commented
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4051

2022-11-24 04:47 UTC, SunithaGudisagarIBM commented
```
sunitha@Sunithas-MacBook-Pro vpc-ibm-lb-config % terraform show
# data.ibm_is_security_group_rule.example:
data "ibm_is_security_group_rule" "example" {
    code                = 256
    direction           = "inbound"
    href                = "https://us-south.iaas.cloud.ibm.com/v1/security_groups/r006-1f31afb0-416e-4ddc-9a04-1f87343aa8fd/rules/r006-0e257e96-ac9e-4861-921d-0823501cf025"
    id                  = "r006-0e257e96-ac9e-4861-921d-0823501cf025"
    ip_version          = "ipv4"
    protocol            = "icmp"
    remote              = [
        {
            address    = "127.0.0.1"
            cidr_block = ""
            crn        = ""
            deleted    = []
            href       = ""
            id         = ""
            name       = ""
        },
    ]
    security_group      = "r006-1f31afb0-416e-4ddc-9a04-1f87343aa8fd"
    security_group_rule = "r006-0e257e96-ac9e-4861-921d-0823501cf025"
    type                = 30
}
```

2022-11-29 05:07 UTC, ujjwal-ibm requested changes

2022-11-29 05:07 UTC, ujjwal-ibm commented on ibm/service/vpc/resource_ibm_is_security_group_rule.go
> +	// parsed.icmpType = -1
remove commented code

2022-11-29 05:07 UTC, ujjwal-ibm commented on ibm/service/vpc/resource_ibm_is_security_group_rule.go
> +							Default:      255,
add test cases

2022-12-01 05:39 UTC, closed without merging