Support for vpc default routing table
ibm-vpc/terraform-provider-ibm pull request #242
Opened 2023-02-02 07:29 UTC by ujjwal-ibm

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2023-02-17 05:09 UTC, SunithaGudisagarIBM requested changes
Hi Ujjwal, 

Please find my review comments here.

Thank you 
Sunitha

Tested with the below configuration -
```
resource "ibm_is_vpc" "testacc_vpc" {
	name = "sunitha-tfp-test-vpc"
}
resource "ibm_is_vpc_default_routing_table" "test_ibm_is_vpc_default_routing_table" {
	depends_on = [ibm_is_vpc.testacc_vpc]
	/* vpc = ibm_is_vpc.testacc_vpc.id */
	/* name = "sunitha-tfp-test-vpc-reouting" */
	accept_routes_from_resource_type=["vpn_server"]
}
```
<img width="829" alt="Screenshot 2023-02-17 at 10 38 37 AM" src="https://user-images.githubusercontent.com/78336632/219554422-cc1cf3e2-a7e0-41cc-814c-479fb7a4f894.png">
<img width="1037" alt="Screenshot 2023-02-17 at 10 38 50 AM" src="https://user-images.githubusercontent.com/78336632/219554465-b4d65d75-ce41-4006-ad58-c608feecb53f.png">

2023-02-17 05:09 UTC, SunithaGudisagarIBM commented on ibm/service/vpc/resource_ibm_is_vpc_default_routing_table.go
> +			rtVpcID: {
it's computed and force new, hence getting the below error
<img width="957" alt="Screenshot 2023-02-17 at 10 35 00 AM" src="https://user-images.githubusercontent.com/78336632/219553959-bfd6d398-f284-45e1-8e9b-f7008a2851a2.png">

2023-02-17 05:09 UTC, SunithaGudisagarIBM commented on ibm/service/vpc/resource_ibm_is_vpc_default_routing_table.go
> +			},
it's computed field hence receiving below error
<img width="1039" alt="Screenshot 2023-02-17 at 10 35 46 AM" src="https://user-images.githubusercontent.com/78336632/219554050-1feb97b2-5b3f-4920-8cd0-b7bb5ea10d62.png">

2023-02-17 05:09 UTC, SunithaGudisagarIBM commented on ibm/service/vpc/resource_ibm_is_vpc_default_routing_table_test.go
> +	vpc = ibm_is_vpc.testacc_vpc.id
Name and VPC as mentioned in the above comment, please change this accordingly.
and without VPC id getting the below error, please modify the acceptance testing accordingly..
<img width="888" alt="Screenshot 2023-02-17 at 10 36 52 AM" src="https://user-images.githubusercontent.com/78336632/219554183-6bb54434-1fae-4513-85ce-2c467123c717.png">

2023-02-17 05:09 UTC, SunithaGudisagarIBM commented on website/docs/r/is_vpc_default_routing_table.html.markdown
> +  vpc                           = ibm_is_vpc.example.id
same applies here also

2023-04-03 05:09 UTC, ujjwal-ibm commented
moving to upstream

2023-04-03 05:09 UTC, closed without merging