Backup policy development
ibm-vpc/terraform-provider-ibm pull request #243
Opened 2023-02-02 16:16 UTC by SunithaGudisagarIBM

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2023-02-08 10:14 UTC, BShrivastav requested changes
Add the acceptance tests and attach the results along please.

2023-02-17 09:02 UTC, BShrivastav reviewed
Hi, This looks fine. Just verify the suggestion given. Consider this approved ones that comments i sorted.

2023-02-17 09:02 UTC, BShrivastav commented on ibm/service/vpc/resource_ibm_is_lb_listener.go
> +		log.Println("if d.HasChange(isLBListenerIdleConnectionTimeout) {}")
Is this required?

2023-02-23 05:18 UTC, SunithaGudisagarIBM commented on ibm/service/vpc/resource_ibm_is_lb_listener.go
> +		log.Println("if d.HasChange(isLBListenerIdleConnectionTimeout) {}")
Done

2023-03-09 16:28 UTC, SunithaGudisagarIBM commented
<img width="767" alt="Screenshot 2023-03-09 at 9 55 26 PM" src="https://user-images.githubusercontent.com/78336632/224088576-51419348-3bf4-44b3-9202-9f62d1b9a3e0.png">

2023-03-13 12:48 UTC, closed without merging