feat(billing-metering): Billing and Metering to support plan crn in catalog offering
ibm-vpc/terraform-provider-ibm pull request #339
Opened 2024-02-22 04:16 UTC by sreekarbvibm

2024-02-22 04:32 UTC, ujjwal-ibm requested changes

2024-02-22 04:32 UTC, ujjwal-ibm commented on website/docs/r/is_instance.html.markdown
> +    plan_crn = "crn:v1:staging:public:globalcatalog-collection:global::1082e7d2-5e2f-0a11-a3bc-f88a8e1931fc:plan:sw.1082e7d2-5e2f-0a11-a3bc-f88a8e1931fc.7c7210da-bc40-418f-9a0a-af994040c13c-global"
missing documents for all resources and datasources

2024-02-22 04:32 UTC, ujjwal-ibm commented on ibm/service/vpc/resource_ibm_is_volume.go
> +		d.Set(isVolumeCatalogOffering, catalogList)
set it empty outside nil check

2024-02-22 04:32 UTC, ujjwal-ibm commented on ibm/service/vpc/resource_ibm_is_snapshot.go
> +		}
set it outside nil as empty if comes empty

2024-02-29 04:31 UTC, sreekarbvibm commented
[config.tf.txt](https://github.com/ibm-vpc/terraform-provider-ibm/files/14442824/config.tf.txt)
<img width="1719" alt="terraform_apply_output" src="https://github.com/ibm-vpc/terraform-provider-ibm/assets/139211144/bd0096b4-b1cf-40dd-9016-e170b6a88753">
<img width="1011" alt="terraform_plan" src="https://github.com/ibm-vpc/terraform-provider-ibm/assets/139211144/549c283c-4f44-4d48-8e14-d43c09df2b79">
[terraform.log](https://github.com/ibm-vpc/terraform-provider-ibm/files/14442826/terraform.log)

2024-10-24 07:25 UTC, ujjwal-ibm approved these changes

2024-12-11 15:08 UTC, closed without merging