Development Public Address Range
ibm-vpc/terraform-provider-ibm pull request #377
Opened 2024-08-30 07:22 UTC by SunithaGudisagarIBM1

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2024-08-30 07:24 UTC, SunithaGudisagarIBM1 commented
```
resource "ibm_is_public_address_range" "public_address_range_instance" {
	ipv4_address_count = "16"
}
```
	
<img width="1109" alt="Screenshot 2024-08-30 at 12 54 04 PM" src="https://github.com/user-attachments/assets/4eb7670f-8303-4d13-9d5a-0681aa1189e8">

2024-08-30 08:06 UTC, SunithaGudisagarIBM1 commented
Update Testing
<img width="1031" alt="Screenshot 2024-08-30 at 1 36 30 PM" src="https://github.com/user-attachments/assets/c796e1aa-8a63-4a23-a25c-a634b0b0812e">

2024-08-30 08:35 UTC, SunithaGudisagarIBM1 commented
```
resource "ibm_is_public_address_range" "public_address_range_instance" {
	ipv4_address_count = "16"
  name = "example-public-address-range"
  resource_group{
      id = "11caaa983d9c4beb82690daab08717e9"
  }
  target{
    vpc {
      id = ibm_is_vpc.testacc_vpc.id
    }
    zone {
      name = "us-south-3"
    }
  }
}
```

<img width="1121" alt="Screenshot 2024-08-30 at 2 04 37 PM" src="https://github.com/user-attachments/assets/d413fba5-616d-440d-8d7d-83d1e6e22221">

2024-08-30 09:50 UTC, SunithaGudisagarIBM1 commented
```
data "ibm_is_public_address_ranges" "public_address_range_instances_example_testing" {
}
```
<img width="1123" alt="Screenshot 2024-08-30 at 3 20 11 PM" src="https://github.com/user-attachments/assets/1910e325-0184-412a-b808-3a3c673a1581">

2024-08-30 12:31 UTC, ujjwal-ibm commented on website/docs/d/is_public_address_ranges.html.markdown
> +- `resource_group_id` - (String) The ID of the Resource group this public gateway belongs to.
(optional) is missing

2024-08-30 12:32 UTC, ujjwal-ibm commented on ibm/service/vpc/resource_ibm_is_virtual_network_interface.go
> +	// sess, err := vpcClient(meta)
rebase, this issue would be resolved

2024-08-30 12:33 UTC, ujjwal-ibm commented on ibm/service/vpc/data_source_ibm_is_bare_metal_server.go
> +	// if err != nil {
rebase should resolve this

2024-08-30 12:35 UTC, ujjwal-ibm commented on ibm/service/vpc/data_source_ibm_is_public_address_range.go
> +		return diag.FromErr(err)
follow the same error pattern as in other places.


		tfErr := flex.TerraformErrorf(err, err.Error(), "(Data) ibm_is_public_address_range", "read")
		log.Printf("[DEBUG]\n%s", tfErr.GetDebugMessage())
		return tfErr.GetDiag()

2024-08-30 12:36 UTC, ujjwal-ibm commented on website/docs/d/is_public_address_ranges.html.markdown
> +- `resource_group_id` - (String) The ID of the Resource group this public gateway belongs to.
code says resource group, here resource_group_id is specified

2024-08-30 12:37 UTC, ujjwal-ibm commented on ibm/service/vpc/data_source_ibm_is_public_address_ranges.go
> +			"resource_group": &schema.Schema{
in docs its resource_group_id

2024-08-30 12:38 UTC, ujjwal-ibm commented on ibm/service/vpc/resource_ibm_is_public_address_range.go
> +	vpcClient, err := vpcClient(meta)
same

2024-09-03 03:11 UTC, astha-jain commented on website/docs/d/is_public_address_range.html.markdown
> +- `target` - (List) The target this public address range is bound to.If absent, this pubic address range is not bound to a target.
Spelling of word public

2024-09-03 03:11 UTC, astha-jain commented on website/docs/d/is_public_address_ranges.html.markdown
> +	- `target` - (List) The target this public address range is bound to.If absent, this pubic address range is not bound to a target.
same

2024-09-03 03:11 UTC, astha-jain commented on website/docs/r/is_public_address_range.html.markdown
> +- `target` - (Optional, List) The target this public address range is bound to.If absent, this pubic address range is not bound to a target.
same

2024-09-03 03:16 UTC, astha-jain commented on website/docs/r/is_public_address_range.html.markdown
> +}
Can I see an example for unbind a Public Address Range from a VPC?

2024-09-03 03:18 UTC, astha-jain requested changes
VPC resource and datasource need to reflect the public address ranges in the responses.

2024-09-03 18:08 UTC, SunithaGudisagarIBM1 commented
```
data "ibm_is_vpc" "ds_vpc_by_id" {
  identifier = "r134-5d3a4aaa-9400-42e6-b035-a1c37a0fb3be"
}
```
<img width="1125" alt="Screenshot 2024-09-03 at 11 38 00 PM" src="https://github.com/user-attachments/assets/3f1625e7-4b22-4eb9-a22c-709fa69b512d">

2024-09-03 18:09 UTC, SunithaGudisagarIBM1 commented
```
data "ibm_is_vpcs" "ds_vpc_by_id" {
}
```
<img width="1127" alt="Screenshot 2024-09-03 at 11 38 50 PM" src="https://github.com/user-attachments/assets/5bba9d32-4408-4515-8ef5-c12abf8c6021">

2025-07-09 16:12 UTC, closed without merging