fix(egw): endpoint gateway access pending
ibm-vpc/terraform-provider-ibm pull request #388
Opened 2024-10-22 05:18 UTC by deepaksibm

2024-10-23 02:52 UTC, ujjwal-ibm requested changes

2024-10-23 02:52 UTC, ujjwal-ibm commented on ibm/service/vpc/resource_ibm_is_virtual_endpoint_gateway.go
> +			if err != nil {
err is not nil here already

2024-10-29 10:46 UTC, deepaksibm commented
```
$ tfpt TestAccIBMISVirtualEndpointGateway_Basic
=== RUN   TestAccIBMISVirtualEndpointGateway_Basic
--- PASS: TestAccIBMISVirtualEndpointGateway_Basic (127.32s)
=== RUN   TestAccIBMISVirtualEndpointGateway_Basic_SecurityGroups
--- PASS: TestAccIBMISVirtualEndpointGateway_Basic_SecurityGroups (127.51s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     258.040s


$ tfpt TestAccIBMISVirtualEndpointGateway_PPSG_With_AccessPolicy_Review_And_Timeout
=== RUN   TestAccIBMISVirtualEndpointGateway_PPSG_With_AccessPolicy_Review_And_Timeout
--- PASS: TestAccIBMISVirtualEndpointGateway_PPSG_With_AccessPolicy_Review_And_Timeout (1997.14s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     2000.278s
```

2024-10-29 10:46 UTC, deepaksibm commented on ibm/service/vpc/resource_ibm_is_virtual_endpoint_gateway.go
> +			if err != nil {
updated the logic

2024-12-16 05:18 UTC, deepaksibm commented
Upstream PR merged

2024-12-16 05:18 UTC, closed without merging